[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
uart_16550 = "0.3.0"
common = { workspace = true }
x86_64 = "0.15.1"
uefi = { version = "0.28.0", default-features = false }
log = "0.4.21"
spin = "0.9.8"
