[package]
name = "bootloader"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"
x86_64 = "0.14.8"
serde-json-core = "0.5.0"
uefi = "0.20.0"
bootloader_api = "0.11.7"
bootloader-boot-config = "0.11.7"
bootloader-x86_64-common = "0.11.7"
xmas-elf = "0.8.0"
